#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd.
# Your script should only display:
# username
# user id
# Home directory path for the user

while x=":" read -r FILE
do
    echo "$FILE" | cut -d":" -f1,3,6
done </etc/passwd
