#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# On the 9th iteration, displays "Hi" before "Best School"

i=1

while [ $i -lt 11 ];
do
	if [ $i -eq 10 ];
	then
		echo "Hi"
	fi
	echo "Best School"
	((i++))
done
