#!/usr/bin/env bash
# A Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

i=$(ls)
for i in $i
do
	echo "$i" | cut -d "-" -f2
done
