#!/usr/bin/env bash
# A Bash script that gives you information about the school file

if [ -f "school" ]
    then
	echo "school file exits"
    if [ -s "school" ]
    then
	echo "school file is not empty"
	else
		echo "school file is empty"
		fi
		if [ -f "school" ]
			then
			echo "school file is a regular file"
			fi
else
	echo "school file does not exist"
fi
